### ISSUE TITLE
socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by shareitcode** [grwl/sslcaudit#51]
When I run this command :
`sudo ./abbbe-sslcaudit-809ce7f/sslcaudit -l 127.0.0.1:443`
I haved this result :
<pre>
<code>
Traceback (most recent call last):
  File "./abbbe-sslcaudit-809ce7f/sslcaudit", line 20, in <module>
    sys.exit(main(sys.argv))
  File "./abbbe-sslcaudit-809ce7f/sslcaudit", line 13, in main
    main = Main(argv[1:])
  File "/home/jbmathieu/abbbe-sslcaudit-809ce7f/src/Main.py", line 104, in __init__
    self.server = ClientAuditorServer(listen_on, self.auditor_sets)
  File "/home/jbmathieu/abbbe-sslcaudit-809ce7f/src/ClientAuditor/ClientAuditorServer.py", line 60, in __init__
    self.tcp_server = ClientAuditorTCPServer(self.listen_on)
  File "/home/jbmathieu/abbbe-sslcaudit-809ce7f/src/ClientAuditor/ClientAuditorServer.py", line 33, in __init__
    self.server_activate()
  File "/usr/lib/python2.7/SocketServer.py", line 440, in server_activate
    self.socket.listen(self.request_queue_size)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
</code>
</pre>

OS : Linux debian-server 4.9.0-8-amd64 1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux / debian-9.3.0-amd64-netinst

I launched Apache2 and I can access to my website to HTTPS.

I install SSL with this tutoriel : http://www.ixany.org/docs/SSL_AC_locale.html

**Comment by abbbe** [comment]
SSLCAUDIT is for testing _clients_, not servers.
If you want to test your Apache setup, better use https://www.bolet.org/TestSSLServer/
